export { ReactComponent as TranslationIcon } from './translation-icon.svg';
export { ReactComponent as FacebookIcon } from './facebook-logo.svg';
export { ReactComponent as WhatsappIcon } from './whatsapp-logo.svg';
export { ReactComponent as TwitterIcon } from './twitter-logo.svg';
export { ReactComponent as LinkedinIcon } from './linkedin-logo.svg';
export { ReactComponent as InstagramIcon } from './instagram-logo.svg';
export { ReactComponent as ShareIcon } from './share-logo.svg';
export { ReactComponent as RightArrowIcon } from './right-arrow.svg';
export { ReactComponent as RightArrowIconThick } from './right-arrow-thick.svg';